### ISSUE TITLE
Special characters and line reading

### ISSUE THREAD

**Issue by zmarouf** [enquirer/readline-utils#2]
Hello!

I've been fiddling with enquirer and I had a quick question. 

I'm using enquirer 0.4.1 (read-utils 0.1.3)

If I press on a special character keyboard key (comma, brackets etc.) they don't show up until I press on a valid key (alphanumeric etc.)
I managed to track down the code responsible for this behavior:
https://github.com/enquirer/readline-utils/blob/master/index.js#L277
```javascript
  if (!event.key.name || is('enter') || is('return')) return;
```
In the following GIF, I repeatedly press the comma key and finally hit the space bar. As you can see, the commas appear all at once. I change the code, execute your prompt example file and we see the "expected" behaviour.

![readline-utils](https://cloud.githubusercontent.com/assets/4321056/24074442/be13e848-0c08-11e7-80bf-44e8b01050c8.gif)

I say "expected" because I have a feeling that you're trying to filter out something with this test which would mean it's there for a reason. 

If that's indeed the case, would you be so kind as to guide me unto achieving what I want without breaking your test? 
If not, should I just submit a PR to change the line?

Thank you for your time! :)

**Comment by doowb** [comment]
Hi @zmarouf thanks for the thorough issue. See [this issue](https://github.com/enquirer/prompt-base/issues/5) for a related discussion.

We'll keep this issue open since this is the correct place to fix it. @jonschlinkert and I have discussed some other approaches that we'll be implementing soon.

In the meantime, I think we could do a bug fix to ensure that unnamed keys get emitted.
I think the following change to the line you pointed out will be sufficient for the bug fix:

```js
if (!event.key.name) {
  if (is('enter') || is('return')) {
    return;
  }
  return event;
}
```

Feel free to submit a PR if you'd like, otherwise, we'll get this fixed soon.

**Comment by jonschlinkert** [comment]
> Feel free to submit a PR if you'd like, otherwise, we'll get this fixed soon.

No need, I already have a fix for this locally. I'll get it pushed up asap.

**Comment by zmarouf** [comment]
Great! Thanks for the quick reply :)
