### ISSUE TITLE
no CLI width when not in a TTY

### ISSUE THREAD

**Issue by stevenvachon** [enquirer/readline-utils#4]
```
TypeError: Cannot read property 'width' of undefined
```
as a result of https://github.com/enquirer/readline-utils/blob/master/index.js#L334

Maybe we can provide a default value in this situation?

**Comment by doowb** [comment]
There's an update to `window-size` that will expose other methods to try to get the size if the default one doesn't work. I think we can use those other methods and then just return `undefined` so we don't get the error and a default can be determined by the user.

**Comment by stevenvachon** [comment]
I feel that this one is important for testing CLIs that use Enquirer, preferably with [suppose](https://npmjs.com/suppose).

**Comment by doowb** [comment]
I'm already working on an update to ensure the `TypeError: Cannot read property 'width' of undefined` is not thrown and different attempts are made to get the window size.

However, because you linked to this in the `window-size` issue and mentioned `pty.js`, I did a quick test and it looks like `window-size` is able to get the size that's provided to `pty.js`. There might be something else in `suppose` or someplace that is causing the values not to be set correctly.

Here's the quick test I ran:

**simple file to run that shows the value from `window-size`**

```js
// size.js
'use strict';

var size = require('window-size');
console.log(size);
```
**pty file to run `size.js` based on the default example in the `pty.js` readme**

```js
// foo.js
var pty = require('pty.js');

var term = pty.spawn('node', ['size.js'], {
  name: 'xterm-color',
  cols: 60,
  rows: 30,
  cwd: __dirname,
  env: process.env
});

term.on('data', function(data) {
  console.log(data);
});

console.log(term.process);
```

**results**

![image](https://user-images.githubusercontent.com/995160/28087196-8bf0b76e-664f-11e7-83d5-9944134f01df.png)

To understand what may be different, I think more information is necessary:

 - [ ] which OS are you using
 - [ ] which version of node are you using
 - [ ] please provide your test code (your actual code that throws the error)

You also might want to look at the tests in the different enquirer `prompt-*` libraries to see how we're testing the prompts since we aren't using `suppose`.

**Comment by jonschlinkert** [comment]
> There might be something else in suppose or someplace that is causing the values not to be set correctly.

that's what I concluded as well, after quick testing on my end. but I don't know enough about the other libs.

**Comment by doowb** [comment]
@stevenvachon #5 is a PR with changes to handle ensuring that something is returned from `.cliWidth`. I don't have the environment setup like you do, but the tests are passing on travis (mac and linux) and appeveyor (windows). If you can test out those changes with `suppose` it'd be appreciated.

**Comment by stevenvachon** [comment]
@doowb it works!

**Comment by doowb** [comment]
Great! I merged in the changes and will publish in a little bit.

**Comment by stevenvachon** [comment]
Thanks!
